import datetime
import logging
from typing import Dict, List, Any, Optional
from collections import defaultdict

logger = logging.getLogger(__name__)

class AlertSignal:
    """Represents a discrete predictive signal from a specific ML or algorithmic module."""
    def __init__(self, source: str, timestamp: datetime.datetime, score: float, description: str):
        self.source = source
        self.timestamp = timestamp
        self.score = score
        self.description = description

class PMLATypologyMapper:
    """
    Automated compliance mapping matrix and multi-signal corroboration gate.
    Designed for India's Prevention of Money Laundering Act (PMLA) mandates.
    
    Enforces strict 24-hour sliding window corroboration before escalating alerts
    and generates FIU-IND specific compliance metadata with countdown timers.
    """
    
    # 15 Standard FIU-IND Typologies Matrix
    TYPOLOGIES = {
        "TYP-01": "High-volume structuring via digital wallets",
        "TYP-02": "Dynamic round-tripping through shell entities",
        "TYP-03": "Rapid layering across multiple payment rails",
        "TYP-04": "Mule account activation after prolonged dormancy",
        "TYP-05": "Cross-border smurfing via cryptocurrency gateways",
        "TYP-06": "Trade-based money laundering (TBML) value mismatches",
        "TYP-07": "Politically Exposed Person (PEP) hidden shell structures",
        "TYP-08": "Terrorist financing small-value distributed networks",
        "TYP-09": "High-risk jurisdiction swift transfers",
        "TYP-10": "Unregistered MSB/Hawala proxy pooling",
        "TYP-11": "Real estate cash infusion anomalies",
        "TYP-12": "NGO/Charity fund diversion layering",
        "TYP-13": "Casino/Gaming high-velocity chip turnover",
        "TYP-14": "Corporate account circular flow structures",
        "TYP-15": "Prepaid card localized anonymous loading",
    }
    
    # Algorithmic source to primary & secondary typology heuristic mapping
    SOURCE_TO_TYPOLOGY_MAP = {
        "FLINK_CEP_STRUCTURING": ["TYP-01", "TYP-03"],
        "ROUND_TRIPPING_TRACER": ["TYP-02", "TYP-14"],
        "RAPID_LAYERING_ANALYZER": ["TYP-03", "TYP-01"],
        "DORMANT_ACTIVATION_MONITOR": ["TYP-04", "TYP-10"],
        "ISOLATION_FOREST_ANOMALY": ["TYP-05", "TYP-09"],
        "GRAPHSAGE_NETWORK_RISK": ["TYP-07", "TYP-02"],
        "XGBOOST_RISK_ENGINE": ["TYP-06", "TYP-11"],
    }
    
    def __init__(self, time_window_hours: int = 24):
        """
        Initializes the PMLA Typology Mapper with a strict temporal corroboration window.
        
        Args:
            time_window_hours: The maximum sliding window duration to link independent signals (default 24h).
        """
        self.time_window = datetime.timedelta(hours=time_window_hours)
        # Stateful tracking matrix for entities: entity_id -> List[AlertSignal]
        self._state_store: Dict[str, List[AlertSignal]] = defaultdict(list)
        
    def register_signal(
        self, 
        entity_id: str, 
        source: str, 
        score: float, 
        description: str, 
        current_time: Optional[datetime.datetime] = None
    ) -> Dict[str, Any]:
        """
        Registers an incoming predictive signal and evaluates multi-signal corroboration.
        Automatically stamps fully corroborated alerts with PMLA statutory metadata.
        
        Args:
            entity_id: The unique identifier for the customer, account, or IP cluster.
            source: The originating detector module (e.g., "FLINK_CEP_STRUCTURING").
            score: The raw anomaly or risk score generated by the source.
            description: Contextual description of the detected event.
            current_time: Execution timestamp (defaults to current UTC time).
            
        Returns:
            Dictionary payload representing the finalized risk alert for the investigator queue.
        """
        if current_time is None:
            current_time = datetime.datetime.now(datetime.timezone.utc)
            
        new_signal = AlertSignal(source, current_time, score, description)
        
        # 1. Prune historical signals outside the sliding 24-hour temporal window
        valid_signals = [
            sig for sig in self._state_store[entity_id] 
            if current_time - sig.timestamp <= self.time_window
        ]
        
        # 2. Append new signal to state
        valid_signals.append(new_signal)
        self._state_store[entity_id] = valid_signals
        
        # 3. Evaluate independent multi-signal corroboration
        distinct_sources = set(sig.source for sig in valid_signals)
        
        # Base alert state
        alert_payload = {
            "entity_id": entity_id,
            "trigger_time": current_time.isoformat(),
            "primary_trigger": source,
            "signals_in_window": len(valid_signals),
            "distinct_sources": list(distinct_sources),
            "severity": "LOW",  # Strictly locked to LOW baseline unless independently corroborated
            "pmla_compliance_metadata": None
        }
        
        # 4. Escalate severity & stamp regulatory payload if corroborated
        if len(distinct_sources) >= 2:
            alert_payload["severity"] = "HIGH" if len(distinct_sources) == 2 else "CRITICAL"
            
            # Map Typologies
            primary_typs = self.SOURCE_TO_TYPOLOGY_MAP.get(source, ["UNKNOWN"])
            primary_code = primary_typs[0]
            
            # Extract highest-value secondary typology from historical signals
            secondary_code = "UNKNOWN"
            for sig in reversed(valid_signals):
                if sig.source != source:
                    sec_typs = self.SOURCE_TO_TYPOLOGY_MAP.get(sig.source, ["UNKNOWN"])
                    if sec_typs[0] != "UNKNOWN":
                        secondary_code = sec_typs[0]
                        break
                        
            # Determine Statutory Sections
            # Section 12 mandates suspicious transaction reporting (STR)
            # Section 16 deals with attachment/freezing of tainted assets
            statutory_section = "Section 12 (PMLA, 2002) - STR Mandate"
            if alert_payload["severity"] == "CRITICAL":
                statutory_section = "Section 12 & 16 (PMLA, 2002) - Imminent Threat / Asset Freezing Review"
                
            # 7-Calendar-Day deadline computation
            deadline_time = current_time + datetime.timedelta(days=7)
            
            # Calculate remaining hours (will be 168.0 exactly at generation, but dynamic if queried later)
            time_delta = deadline_time - current_time
            hours_remaining = time_delta.total_seconds() / 3600.0
            
            alert_payload["pmla_compliance_metadata"] = {
                "primary_typology_code": primary_code,
                "primary_typology_desc": self.TYPOLOGIES.get(primary_code, "Unclassified network anomaly"),
                "secondary_typology_code": secondary_code,
                "secondary_typology_desc": self.TYPOLOGIES.get(secondary_code, "Unclassified network anomaly"),
                "statutory_mandate": statutory_section,
                "fiu_ind_deadline": deadline_time.isoformat(),
                "hours_remaining_until_deadline": round(hours_remaining, 2),
                "corroboration_audit_trail": [
                    {
                        "source": sig.source, 
                        "timestamp": sig.timestamp.isoformat(), 
                        "score": sig.score,
                        "description": sig.description
                    }
                    for sig in valid_signals
                ]
            }
            
            logger.warning(f"CORROBORATED ALERT EXECUTED: Entity {entity_id} escalated to {alert_payload['severity']} severity.")
            
        return alert_payload
